# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dmitry Nets
email: dmitrynets@gmail.com
description: Javascript, front-end, coding & more
url: "http://dnets.github.io/" # the base hostname & protocol for your site
twitter_username: d_nets
github_username:  dnets

# Build settings
markdown: kramdown
permalink: /:title
